//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QOTD.NET.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QOTD.NET.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child classes looking to extend DailyQuoteProvider must override GetNewDayQuote()..
        /// </summary>
        internal static string DailyQuoteProviderDidntOverrideGetNewDayQuote {
            get {
                return ResourceManager.GetString("DailyQuoteProviderDidntOverrideGetNewDayQuote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new quote has been chosen for day {0}: &quot;{1}&quot;..
        /// </summary>
        internal static string DailyQuoteProviderLogNewQuote {
            get {
                return ResourceManager.GetString("DailyQuoteProviderLogNewQuote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The quote pool contains at least one null value..
        /// </summary>
        internal static string DailyQuoteProviderPoolContainsNull {
            get {
                return ResourceManager.GetString("DailyQuoteProviderPoolContainsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The quote pool must have at least one quote..
        /// </summary>
        internal static string DailyQuoteProviderPoolMustHaveElements {
            get {
                return ResourceManager.GetString("DailyQuoteProviderPoolMustHaveElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception was thrown while logging..
        /// </summary>
        internal static string LoggerException {
            get {
                return ResourceManager.GetString("LoggerException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data sent by the server couldn&apos;t be formed into a quote..
        /// </summary>
        internal static string QotdClientReceivedInvalidQuote {
            get {
                return ResourceManager.GetString("QotdClientReceivedInvalidQuote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception was encountered trying to send a UDP request..
        /// </summary>
        internal static string QotdClientTransportError {
            get {
                return ResourceManager.GetString("QotdClientTransportError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A quote was received that contained unknown or invalid characters that couldn&apos;t be handled by the selected encoding ({0})..
        /// </summary>
        internal static string QotdClientUnexpectedCharacterInEncoding {
            get {
                return ResourceManager.GetString("QotdClientUnexpectedCharacterInEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception was thrown by the IQuoteProvider implementation..
        /// </summary>
        internal static string QotdServerExceptionThrownByQuoteProvider {
            get {
                return ResourceManager.GetString("QotdServerExceptionThrownByQuoteProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A quote provided by the IQuoteProvider was truncated because it was longer than the maximum encoded length..
        /// </summary>
        internal static string QotdServerQuoteTruncated {
            get {
                return ResourceManager.GetString("QotdServerQuoteTruncated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception was encountered attempting to send a quote over TCP..
        /// </summary>
        internal static string QotdServerTransportError {
            get {
                return ResourceManager.GetString("QotdServerTransportError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A quote provided by IQuoteProvider contained characters that can&apos;t be handled by the selected encoding ({0})..
        /// </summary>
        internal static string QotdServerUnexpectedCharacterInEncoding {
            get {
                return ResourceManager.GetString("QotdServerUnexpectedCharacterInEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received a request for a quote from {0} over {1}..
        /// </summary>
        internal static string Trace_QotdServerReceiveRequest {
            get {
                return ResourceManager.GetString("Trace_QotdServerReceiveRequest", resourceCulture);
            }
        }
    }
}
